"""Clio legal practice management toolkit for Arcade AI."""

from .client import ClioClient
from .exceptions import (
    ClioAuthenticationError,
    ClioError,
    ClioPermissionError,
    ClioPreconditionError,
    ClioRateLimitError,
    ClioResourceNotFoundError,
    ClioServerError,
    ClioTimeoutError,
    ClioValidationError,
)
from .tools import (
    # Matter tools
    add_matter_participant,
    close_matter,
    # Billing tools
    create_bill,
    # Contact tools
    create_contact,
    # Custom Actions tools
    create_custom_action,
    create_expense,
    create_matter,
    create_time_entry,
    # Webhook tools
    create_webhook,
    delete_custom_action,
    delete_webhook,
    # Timer tools
    get_active_timer,
    get_bills,
    get_contact,
    get_contact_relationships,
    get_custom_action,
    get_expenses,
    get_matter,
    get_matter_activities,
    get_time_entries,
    get_webhook,
    list_contact_activities,
    list_custom_actions,
    list_matters,
    list_webhooks,
    pause_timer,
    remove_matter_participant,
    search_contacts,
    start_timer,
    stop_timer,
    test_custom_action_url,
    update_contact,
    update_custom_action,
    update_matter,
    update_time_entry,
    update_webhook,
    # Activity tools
    delete_activity,
    get_activity,
    list_activities,
    # Document tools
    create_document,
    delete_document,
    get_document,
    list_documents,
    update_document,
)

__version__ = "0.1.0"

__all__ = [
    "ClioAuthenticationError",
    "ClioClient",
    "ClioError",
    "ClioPermissionError",
    "ClioPreconditionError",
    "ClioRateLimitError",
    "ClioResourceNotFoundError",
    "ClioServerError",
    "ClioTimeoutError",
    "ClioValidationError",
    "add_matter_participant",
    "close_matter",
    "create_bill",
    "create_custom_action",
    "delete_custom_action",
    "get_custom_action",
    "list_custom_actions",
    "test_custom_action_url",
    "update_custom_action",
    "create_contact",
    "create_expense",
    "create_matter",
    "create_time_entry",
    "get_bills",
    "get_contact",
    "get_contact_relationships",
    "get_expenses",
    "get_matter",
    "get_matter_activities",
    "get_time_entries",
    "list_contact_activities",
    "list_matters",
    "remove_matter_participant",
    "search_contacts",
    "update_contact",
    "update_matter",
    "update_time_entry",
    # Timer tools
    "get_active_timer",
    "pause_timer",
    "start_timer",
    "stop_timer",
    # Webhook tools
    "create_webhook",
    "delete_webhook",
    "get_webhook",
    "list_webhooks",
    "update_webhook",
    # Activity tools
    "delete_activity",
    "get_activity",
    "list_activities",
    # Document tools
    "create_document",
    "delete_document",
    "get_document",
    "list_documents",
    "update_document",
]
